# Generated by Django 4.2.2 on 2024-03-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Named', models.CharField(max_length=50)),
                ('legal_form', models.CharField(max_length=50)),
                ('address_social_headquarters', models.CharField(max_length=50)),
                ('name_coordinator_transaction_and_nickname', models.CharField(max_length=100)),
                ('commercial_registration_no', models.IntegerField()),
                ('date_of_commercial', models.DateField()),
                ('card_number_artisan', models.IntegerField()),
                ('date_of_artisan', models.DateField()),
            ],
        ),
    ]
