# Generated by Django 4.2.2 on 2024-03-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_moral_person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moral',
            name='block_plan',
            field=models.FileField(default=1, upload_to='block_plan/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moral',
            name='property_contract',
            field=models.FileField(default=1, upload_to='property_contract/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moral',
            name='report',
            field=models.FileField(default=1, upload_to='report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moral',
            name='site_plan',
            field=models.FileField(default=1, upload_to='site_plan/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moral',
            name='technical_data_sheet',
            field=models.FileField(default=1, upload_to='technical_data_sheet/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moral',
            name='written_request',
            field=models.FileField(default=1, upload_to='written_request/'),
            preserve_default=False,
        ),
    ]
