# Generated by Django 4.2.2 on 2024-03-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_moral_person', '0002_moral_block_plan_moral_property_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moral',
            name='report',
            field=models.FileField(upload_to='report/'),
        ),
    ]
