# Generated by Django 4.2.2 on 2024-03-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('classification_of_the_establishment', models.CharField(max_length=300)),
                ('decree_number', models.IntegerField()),
                ('date_of_decree_issuance', models.DateField()),
                ('public_inquiry_number', models.IntegerField()),
                ('date_of_public_inquiry_issuance', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('start_date_of_the_duration', models.DateField()),
                ('end_date_of_the_duration', models.DateField()),
                ('request_of_mr', models.CharField(max_length=75)),
                ('exploitation_of_the_classified_establishment', models.CharField(max_length=75)),
                ('located_in', models.CharField(max_length=75)),
                ('designation', models.CharField(max_length=75)),
            ],
        ),
    ]
