# Generated by Django 4.2.2 on 2024-03-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reports_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
