# Generated by Django 4.2.2 on 2024-03-27 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_reports_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('titl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplly_job', to='report.reports')),
            ],
        ),
    ]
