# Generated by Django 4.2.2 on 2024-03-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('moral_person', 'شخص معنوي'), ('normal_person', 'شخص طبيعي')], default='normal_person', max_length=20),
        ),
    ]
